import { Page } from "ui_page.slint";
import { UIBarChart } from "ui_bar_chart.slint";
import { VSpace, HSpace } from "ui_space.slint";
import { UIPannel } from "ui_panel.slint";
import { UILineChart } from "ui_line_chart.slint";
import { UIBlockChart } from "ui_block_chart.slint";
import { Theme } from "ui_theme.slint";
import { UIBubbleChart } from "ui_bubble_chart.slint";

export component ComponentPage2 inherits Page {
    
    in property <bool> page-visible;

    VSpace {size: 20px;}

    HorizontalLayout {

        UIBarChart {
            bar-width: 14px;
            bar-border-radius: 4px;
            bar-gap: 7px;
            x-axis-name: "Age";
            y-axis-name: "Score";
            width: 300px;
            height: 200px;
            page-visible: root.page-visible;
            items: [
                {
                    x-axis: 0,
                    y-axis: 50,
                    title: "Check",
                },
                {
                    x-axis: 10,
                    y-axis: 20,
                    title: "Check",
                }
                ,
                {
                    x-axis: 20,
                    y-axis: 30,
                    title: "Check",
                },
                {
                    x-axis: 30,
                    y-axis: 50,
                    title: "Check",
                },
                {
                    x-axis: 40,
                    y-axis: 20,
                    title: "Check",
                },
                {
                    x-axis: 50,
                    y-axis: 30,
                    title: "Check",
                },
                {
                    x-axis: 60,
                    y-axis: 50,
                    title: "Check",
                },
                {
                    x-axis: 70,
                    y-axis: 20,
                    title: "Check",
                }
                ,
                {
                    x-axis: 80,
                    y-axis: 30,
                    title: "Check",
                },
                {
                    x-axis: 90,
                    y-axis: 50,
                    title: "Check",
                },
                {
                    x-axis: 100,
                    y-axis: 20,
                    title: "Check",
                }
                ,
                {
                    x-axis: 110,
                    y-axis: 30,
                    title: "Check",
                }
                ,
                {
                    x-axis: 120,
                    y-axis: 100,
                    title: "Check",
                }
            ];
        }

        HSpace {size: 20px;}
        
        UIPannel {
            width: 200px;
            height: 200px;
            title: "CPU Usage";
        }

    }

    VSpace {size: 30px;}

    HorizontalLayout {
        UILineChart {
            items: [
                {
                    x-axis: 0,
                    y-axis: 50,
                    title: "Check",
                },
                {
                    x-axis: 10,
                    y-axis: 20,
                    title: "Check",
                }
                ,
                {
                    x-axis: 20,
                    y-axis: 30,
                    title: "Check",
                },
                {
                    x-axis: 30,
                    y-axis: 50,
                    title: "Check",
                },
                {
                    x-axis: 40,
                    y-axis: 20,
                    title: "Check",
                },
                {
                    x-axis: 50,
                    y-axis: 30,
                    title: "Check",
                },
                {
                    x-axis: 60,
                    y-axis: 50,
                    title: "Check",
                },
                {
                    x-axis: 70,
                    y-axis: 20,
                    title: "Check",
                }
                ,
                {
                    x-axis: 80,
                    y-axis: 30,
                    title: "Check",
                },
                {
                    x-axis: 90,
                    y-axis: 50,
                    title: "Check",
                },
                {
                    x-axis: 100,
                    y-axis: 20,
                    title: "Check",
                }
                ,
                {
                    x-axis: 110,
                    y-axis: 30,
                    title: "Check",
                }
                ,
                {
                    x-axis: 120,
                    y-axis: 100,
                    title: "Check",
                }
            ];
        }

        HSpace {size: 20px;}

        UIBlockChart {
            title: "Application";
            model: [
                {
                    num: 15,
                    name: "Visual Studio",
                    color: Theme.palette.error-color,
                },
                {
                    num: 20,
                    name: "Idea",
                    color: Theme.palette.warn-color,
                },
                {
                    num: 10,
                    name: "QtCreator",
                    color: Theme.palette.light-main-color,
                },
                {
                    num: 55,
                    name: "VS Code",
                    color: Theme.palette.main-color,
                },
            ];
        }
    }

    VSpace {size: 330px;}

    HorizontalLayout {
        UIBubbleChart {

        }
    }
}