import { Theme } from "ui_theme.slint";

export component UIButton inherits Rectangle {

    in property <bool> selected: false;
    in property <string> text: "Default";
    in property <length> text-size: 14px;
    in property <brush> bg-color: Theme.palette.main-color;
    in property <brush> text-color: #FFFFFF;
    in property <length> out-border-size: 8px;

    callback button-clicked <=> ta.clicked;

    width: 110px;
    height: 30px;
    border-radius: out-border-size;
    background: ta.pressed || selected ? bg-color.darker(30%) :ta.has-hover? bg-color.darker(15%) : bg-color;

    Text {
        text: text;
        font-size: text-size;
        color: text-color;
    }

    ta := TouchArea {
        width: 100%;
        height: 100%;
    }
}

export component MainButton inherits UIButton {
    bg-color: Theme.palette.main-color;
}

export component WarnButton inherits UIButton {
    bg-color: Theme.palette.warn-color;
}

export component ErrorButton inherits UIButton {
    bg-color: Theme.palette.error-color;
}

export component LightMainButton inherits UIButton {
    bg-color: Theme.palette.light-main-color;
}



